application: paula-bramwell
version: 1
runtime: go
api_version: go1
handlers:

- url: /assets/images/
  static_dir: assets/images

- url: /assets/css/ 
  static_dir: assets/css
  
- url: /assets/fonts/
  static_dir: assets/fonts
  
- url: /.*
  script: _go_app
